language: java
before_script:
- unset _JAVA_OPTIONS
- cd finish
- chmod +x ../scripts/travisTest.sh
script: ../scripts/travisTest.sh
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: cVlTnHxyBuaqBaiQfqsyJrSuIYHMA/3Dpdh/0jbL5bITo0MmB6wVcJUTIA/8Nnzgi+cI83n13fGhGBrgefbhRCE+tZAdBPeqYxFbZkVg4JJ909dG8BBwS3N3gFtAGhh7gcZwN5fdc+2cGP4kF18uaViWIitGdmHe5p5XnZBuV0JBL1aXRfZOGbxerpBBEuWjIF7O2b69EWkKTb3nyZlctrSgmZeJWG0xZw7Fahbr7en9hpaemEatCsoiNAIN82CH26kiC3lOVzfGq+WZNabMtnd+ZP3AHnKapmoNB32rMLs3v8A5Nx+IPdwBbM1X0o5kjLgXrGwZhwfRkJ+MxPG8qvbCQNFtsXXhOE/PAFZ4nTn3oyWHRQbKJtYS6gzKGmMTF9BqDpoHsUm0isD/km23ainTc2eQOMgqdGMdzKVFO+4ze6BKhIHWO1VeZBTYkuTDN8S5J7BfMOYC4XhpQHaPvkES56zY2N0fek/AdL/aP5kaa0FwfxC3X/QRNQPe0XMd9MNZNCcOAPn1ieRLq25Lq+osm8we531QjUEU/i6PtPt8wyUzvtHW+oY9ckS67F2kBQ4gLzOckm2ekbnX9SHpd/Ze0BYIaSvFVQrVgKZFM3RvWTD6opGxv3FyRF08bqYT1tcEUPNibUqQ0Cs1ldgPkbcjuIjtArWPcPGzA6AmRtY=
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - qa
